### PR TITLE
Add controls for diff wrist

### PR DESCRIPTION
**Pull request by abhaybd**
Tested in simulation, will hold off on merging until tested on robot

### CODE REVIEW

**Review by Geeoon — APPROVED** [review]
Looks good

**Review by Geeoon — CHANGES_REQUESTED** [review]
Backtracking a bit to say that MCP version should be updated

**Review by AyushKulk — APPROVED** [review]
Looks good to me!

**Review by imisaacwu — APPROVED** [review]

**Review by husky-robotics — APPROVED** [review]
Works as far as I can tell

**Pull request merged**
